-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  ALIGNEMENT POST-PUSH — FICHIER VIDÉ, CONSERVÉ COMME NOTE HISTORIQUE     ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
--
-- ⚠️ CE FICHIER NE CONTIENT PLUS AUCUN SQL. Il n'y a plus rien à jouer.
-- Ne pas le passer à `supabase db query` : ce serait un no-op complet.
--
-- CE QU'IL CONTENAIT
-- ------------------
-- Rejouer les migrations sur une base vierge ne reproduisait pas la prod. La
-- comparaison objet par objet des deux schémas (2026-08-11) faisait apparaître
-- 5 familles d'écarts, dont trois étaient des correctifs appliqués À LA MAIN sur
-- la prod et jamais reversés dans une migration. Ce fichier les rattrapait, et
-- devait être joué à la main après chaque `supabase db push` sur un
-- environnement neuf.
--
-- C'était une dette explicite : chacune de ses sections devait à terme devenir
-- une vraie migration horodatée, idempotente, donc no-op sur la prod.
--
-- C'EST FAIT — les 5 familles sont toutes reversées
-- --------------------------------------------------
--   §1  RLS jamais activée sur workshop_builds / workshop_junglepaths
--         → 20260815000002_enable_rls_workshop.sql
--   §2  Triggers updated_at ad-hoc (set_updated_at, todos_updated_at)
--         → 20260815000004_versioning_updated_at_triggers.sql
--   §3  Index + 4 policies ad-hoc de `scenarios`
--         → 20260815000005_versioning_scenarios_adhoc.sql
--   §4a finalize_quest_claim / purchase_cosmetic — prédicat ON CONFLICT
--         → 20260815000001_fix_ledger_on_conflict_predicate.sql
--   §4b prac_player_stats réécrite + prac_related_players / prac_visible_match_ids
--         → 20260815000003_versioning_prac_functions.sql
--
-- Le fichier compagnon `00_pre_versioning_baseline.sql` a lui aussi été promu,
-- en migration 20260529000000_baseline_pre_versioning.sql. Le dossier
-- `supabase/bootstrap/` n'a donc plus de rôle opérationnel : monter un
-- environnement neuf se fait désormais avec `supabase db push`, et rien d'autre.
--
-- ⚠️ CE QUI RESTE MANUEL — le Database Webhook
-- ---------------------------------------------
-- Une seule chose échappe encore aux migrations : le Database Webhook qui
-- déclenche l'Edge Function `prac-notify` sur `tracked_players`. Les webhooks
-- Supabase ne sont pas exportables en migration, et sa définition embarque
-- `PRAC_WEBHOOK_SECRET` en clair dans ses headers — deux raisons de ne pas le
-- committer. Il reste à recréer À LA MAIN dans le dashboard sur tout nouvel
-- environnement : voir AGENTS.md § « Lot 5E — câblage du Database Webhook »,
-- qui porte aussi l'avertissement sur son nom, différent entre prod et test.
--
-- SUPPRESSION DU FICHIER
-- ----------------------
-- Ce fichier est conservé vide plutôt que supprimé parce que trois migrations
-- (20260815000001, 000002, 000003) le citent nommément dans leurs en-têtes comme
-- source de la dette qu'elles reversent. Le supprimer d'un coup rendrait ces
-- références mortes. Décision de le retirer (et de retirer le dossier
-- `supabase/bootstrap/` avec lui) laissée à HORTAL, une fois la Phase C passée.
